---
title: "Workflow in RAPS"
subtitle: "RAPS: R Aid for P Systems"
author: "Xopre"
date: "`r format(Sys.time(), '%d de %B de %Y')`"
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: true
    number_sections: false 
    df_print: kable
    theme: readable
    highlight: default 
codification: "UTF-8"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo = FALSE}
.blackbox {
  padding: 1em;
  background: #F47174;
  color: white;
  /* border: 2px solid orange; */
  border-radius: 10px;
}
.greenbox {
  padding: 1em;
  background: #79d279;
  color: white;
  /* border: 2px solid orange; */
  border-radius: 10px;
}
.center {
  text-align: center;
}

.code {
  font-family: Courier, "Lucida Console", monospace;
}
```

If RAPS is not installed, uncomment the following:
```{r}
# devtools::document() # To update the documentation
# devtools::install() # To install as package
## Or use:
# devtools::install_github("Xopre/RAPS")
```

```{r}
library(RAPS)
```

With the `path2rap()` function we can create a demo rap, with enough rules tu test how the `apply_rule()` function works.

```{r}
my_rap = RAPS::path2rap(demo = 2)
```

We have the following rules:

1. a --> b
2. a --> b*2
3. a --> b*2, c
4. b*2 --> c
5. a, b --> c
6. a, b*2 --> c
7. a, b\*2 --> c\*3
8. a, b\*2 --> c\*3, d\*4
9. a --> lambda
10. [a [ ]'2 --> [a]'2]'1
11. [ [a]'2 --> a [ ]'2]'1
12. a --> NEW

```{r}
my_rap$Rules
```

Let's try them one by one:

FIXME: Modify `apply_rule.R` first.

```{r}
mem_1_objects = list()
rules = my_rap$Rules

for (i in 1:12) {
  print(i)
  objects = my_rap %>%
    apply_rule(rule_id = i) %$% 
    RAP %>% 
    dplyr::filter(id == 1) %$%
    objects
  
  mem_1_objects[[i]] = objects
}
```

Let's give them a look:

```{r}
i = 1
cat("i = ", i )
RAPS::show_rule(rules[i, ])
my_new_rap = my_rap %>%
    apply_rule(rule_id = i) %$%
    RAP

for (i in 1:3) {
  cat("In membrane with label ", i - 1, " we have..")
  print(my_new_rap$objects[[1]])
}

i %<>% sum(1)
```

```{r}
cat("i = ", i )
RAPS::show_rule(rules[i, ])
my_new_rap = my_rap %>%
    apply_rule(rule_id = i) %$%
    RAP

for (i in 1:3) {
  cat("In membrane with label ", i - 1, " we have..")
  print(my_new_rap$objects[[1]])
}

i %<>% sum(1)
```

