---
title: "Gillespie algorithm"
subtitle: "For mono-environmental and multienvironmental P systems"
author: "Xopre"
date: "`r format(Sys.time(), '%d de %B de %Y')`"
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: true
    number_sections: false 
    df_print: kable
    theme: readable
    highlight: default 
codification: "UTF-8"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo = FALSE}
.blackbox {
  padding: 1em;
  background: #F47174;
  color: white;
  /* border: 2px solid orange; */
  border-radius: 10px;
}
.greenbox {
  padding: 1em;
  background: #79d279;
  color: white;
  /* border: 2px solid orange; */
  border-radius: 10px;
}
.center {
  text-align: center;
}

.code {
  font-family: Courier, "Lucida Console", monospace;
}
```

If RAPS is not installed, uncomment the following:
```{r}
# devtools::install_github("Xopre/RAPS")
## Or use (after downloading the project):
# devtools::document() # To update the documentation
# devtools::install() # To install as package
```

```{r}
library(RAPS)
```

# FAS
```{r}
# With load_demo_dataset
fas_rap = RAPS::load_demo_dataset("FAS")

# With PL5
# path = "https://raw.githubusercontent.com/Xopre/psystems-examples/main/plingua5/RAPS/BIG/FAS.xml"
# setwd("~/GitHub/example-psystems/plingua5/RAPS/BIG")
# fas_rap = RAPS::path2rap(path)

fas_rap
```

```{r}
get_Bcl2_from_rap = function(rap) {
  return(rap$Configuration %>%
    dplyr::filter(id == "m") %$%
    objects %>%
      magrittr::extract2(1) %>%
    dplyr::filter(object == "Bcl2") %$%
    multiplicity)
}

get_Bcl2_from_rap(fas_rap)
```

## Only one variable
```{r}
set.seed(1974)
results = fas_rap %>%
  RAPS::alg_det_menv(max_T = 1e-6, verbose = TRUE, debug = FALSE, save_each = get_Bcl2_from_rap)

new_rap = results$final_rap
selected_data = results$selected_data
n_data = length(selected_data)

selected_data = tibble::tibble(i = 1:n_data, multiplicity = selected_data) %>% 
  tidyr::unnest_longer(multiplicity)

```

```{r}
library(ggplot2)

selected_data %>%
  ggplot(aes(x=i, y=multiplicity, group=object)) +
  geom_line(arrow = arrow())+
  geom_point()
```

## Multiple variables in one membrane

```{r}
get_m_objects = function(rap) {
  return(rap$Configuration %>%
    dplyr::filter(id == "m") %$%
    objects %>%
      magrittr::extract2(1))
}

get_m_objects(fas_rap)
```


```{r}
set.seed(1974)
results = fas_rap %>%
  RAPS::alg_det_menv(max_T = 1e-3, verbose = TRUE, debug = FALSE, save_each = get_m_objects)

new_rap = results$final_rap
selected_data = results$selected_data
n_data = length(selected_data)

selected_data = tibble::tibble(i = 1:n_data, selected_data) %>% 
  tidyr::unnest_longer(selected_data) %>%
  tidyr::unnest_wider(selected_data)

diff_objects = unique(selected_data$object)

for (iter in 1:n_data) {
  for (name in diff_objects) {
    if (dim(dplyr::filter(selected_data, object == name & i == iter))[1] == 0) {
      selected_data %<>%
        dplyr::bind_rows(
          tibble::tibble(
            i = iter,
            object = name,
            multiplicity = 0
          )
        )
    }
  }
}

library(ggplot2)

selected_data %>%
  ggplot(aes(x=i, y=multiplicity, group=object, color = object)) +
  geom_line(arrow = arrow()) +
  labs(title = "Evolution of multiplicity") +
  geom_point()
```
## Get `CASP3`
```{r}
library(RAPS)
fas_rap = load_demo_dataset("FAS")
```


```{r}
get_casp3 = function(rap) {
  return(
    rap$Configuration %>%
    dplyr::select(id, objects) %>%
    tidyr::unnest_longer(objects) %>%
    tidyr::unnest_wider(objects) %>%
    dplyr::filter(object == "CASP3")
  )
}

get_casp3(fas_rap)
```

```{r}
set.seed(1974)
results = fas_rap %>%
  RAPS::alg_det_menv(max_T = 1, verbose = 1, debug = FALSE, save_each = get_casp3)

# Launched for max_T = 1

new_rap = results$final_rap
selected_data = results$selected_data
n_data = length(selected_data)

selected_data = tibble::tibble(i = 1:n_data, selected_data) %>% 
  tidyr::unnest_longer(selected_data) %>%
  tidyr::unnest_wider(selected_data)

diff_objects = unique(selected_data$object)

for (iter in 1:n_data) {
  for (name in diff_objects) {
    if (dim(dplyr::filter(selected_data, object == name & i == iter))[1] == 0) {
      selected_data %<>%
        dplyr::bind_rows(
          tibble::tibble(
            i = iter,
            object = name,
            multiplicity = 0
          )
        )
    }
  }
}

library(ggplot2)

selected_data %>%
  dplyr::group_by(id, i) %>%
  ggplot(aes(x=i, y=multiplicity, group=id, color = id)) +
  geom_line(arrow = arrow()) +
  labs(title = "Evolution of multiplicity") +
  geom_point()

```

```{r}
library(ggplot2)

# One of the following

selected_data %>%
  ggplot(aes(x=i, y=multiplicity, group=object)) +
  geom_line(arrow = arrow())+
  geom_point()

selected_data %>%
  ggplot(aes(x=i, y=multiplicity, group=object, color = object)) +
  geom_line(arrow = arrow()) +
  labs(title = "Evolution of multiplicity") +
  geom_point()
```


# Debugging stochastic example with communication rules
```{r}
path = "https://raw.githubusercontent.com/Xopre/psystems-examples/main/plingua5/RAPS/increasing_rules_communication/2%20-%20multi_inside_to_multi_outside_r.xml"

my_rap = path2rap(path, verbose = 0)
my_rap %<>% alg_det_menv(max_T = 0.5, verbose = TRUE, debug = TRUE)
show_rap(my_rap, focus_on = list("OBJ", "MEM" = 0:1))
```


# Minimal stochastic example

```{r}
path = "https://raw.githubusercontent.com/Xopre/psystems-examples/main/plingua5/RAPS/increasing_rules_evolution/0%20-%20a_to_b_stochastic.xml"

my_rap = path2rap(path)
my_rap$Configuration$environment = "synthetic_env"
RAPS::show_rap(my_rap)
```

Now the simulation:
```{r}
my_rap %<>%
  RAPS::alg_det_menv(max_T = 0.5, verbose = TRUE, debug = TRUE)

my_rap %>%
  RAPS::show_rap(focus_on = list("OBJ", "MEM" = 0:1))
```


# **OUTDATED** - Demo stochastic P system
```{r}
my_rap = path2rap(demo = 1)
RAPS::show_rap(my_rap)
```

Now the simulation:
```{r}
my_rap %<>%
  RAPS::alg_det_menv(max_T = 0.5, verbose = TRUE, debug = TRUE)

my_rap %>%
  RAPS::show_rap(focus_on = list("OBJ", "MEM" = 2:3))
```
